remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  'hyper-ts-routing on GitHub':
    - 'https://github.com/thewilkybarkid/hyper-ts-routing'